### PR TITLE
Adds currency to the form-field

### PR DESCRIPTION
**Pull request by JapSeyz**

### CODE REVIEW

**Comment by vyuldashev** [comment]
Hello! Can you provide a screenshot how it will look like, please?

**Comment by JapSeyz** [comment]
Of course, here you go:

screenshot from 2018-09-10 22-45-37

**Comment by vyuldashev** [comment]
I guess it will be aesthetically if currency will be appended to input. What do you think?

**Comment by JapSeyz** [comment]
Added a bootstrap-eque input-addon; taken from here: https://tailwindcomponents.com/component/input-group-add-ons

**Comment by vyuldashev** [comment]
Thanks! Tagged v1.0.3

**Pull request merged**
