### PR TITLE
Nova 4 Support

### PR DESCRIPTION
**Pull request by stefblokdijk**
Since Nova 4 uses Vue 3, the fields weren't rendering on the latest Nova version.

This PR updates the package to support Nova 4 (just for the project i'm using it on) and won't be compatible with previous Nova versions. That is why i'd suggest to release this eventually as a v2 of this package with instructions how Nova 1 - 3 users should install v1 on their project.

Besides the Nova 4 / Vue 3 update, i've also made minor changes to the code styling to match other packages i've came across and i've implemented the new [dependent form field](https://nova.laravel.com/docs/4.0/customization/fields.html#dependent-form-field) feature.

This PR is not 100% release ready since i've not

- Tested each feature
- Updated screenshots

### CODE REVIEW

**Comment by stefblokdijk** [comment]
I've also wrapped the IndexField into a `<div>` instead of `<span>` to allow Nova's text alignment classes. The `Number` field is now aligned to the right by default. This should also resolve issue #10

**Comment by stefblokdijk** [comment]
Note: I've noticed that `resolveUsing` is not displaying the amount on index/details as `$1.00` as before, but it displays as `100`. I've added an `displayUsing` call to make this work. Might want to double check if this is the desired workflow.

**Comment by BinaryKitten** [comment]
Hi @stefblokdijk - since I don't have access to nova 4 - could we organise a meet/chat so can see this working etc. Would be really useful.

**Comment by stefblokdijk** [comment]
Hi @BinaryKitten, i've checked with the Nova team. They said you can send a request to nova@laravel.com for a dev Nova 4 key.

**Pull request merged**
